// mu — public API surface for programmatic callers (SDK + tests).
//
// The CLI lives in src/cli.ts. Both the CLI and any SDK consumer go
// through the same exports here so there is exactly one canonical surface.

export {
  agentKey,
  type CtlLink,
  ctlRuntimeState,
  murmurAvailable,
  type RuntimeState,
  readAgentStates,
  type StateReading,
  type StateSource,
  UNKNOWN_REASON,
} from "./agent-state.js";
export {
  type AbortAgentOptions,
  type AbortResult,
  type AdoptAgentOptions,
  type AdoptAgentResult,
  AgentAbortNeedsCtlError,
  AgentAbortTimeoutError,
  AgentBusyError,
  AgentCtlUnreachableError,
  AgentDiedOnSpawnError,
  AgentExistsError,
  AgentFreshNeedsCtlError,
  AgentNotFoundError,
  AgentNotInWorkstreamError,
  type AgentRow,
  AgentSlashCommandUnsupportedError,
  AgentSpawnCliNotFoundError,
  AgentSpawnStartupError,
  abortAgent,
  adoptAgent,
  type CloseAgentOptions,
  type CloseAgentResult,
  type CommandResolutionResult,
  type CommandResolver,
  checkCommandResolvable,
  closeAgent,
  composeAgentTitle,
  defaultSpawnLivenessMs,
  deleteAgent,
  envVarNameForCli,
  expectsCtl,
  foregroundPgid,
  getAgent,
  getAgentByPane,
  type InsertAgentInput,
  insertAgent,
  isKickSignal,
  isValidAgentName,
  type KickAgentOptions,
  type KickAgentResult,
  type KickProcessExecutor,
  type KickSignal,
  kickAgent,
  type ListLiveAgentsOptions,
  type LiveAgent,
  type LiveAgentsView,
  listAgents,
  listLiveAgents,
  NoForegroundProcessError,
  parsePsTtyOutput,
  readAgent,
  refreshAgentTitle,
  resetCommandResolverForTests,
  resetKickProcessExecutor,
  resolveCliCommand,
  resolveCliCommandWithSource,
  type SendResult,
  type SpawnAgentOptions,
  sendToAgent,
  sendViaTransport,
  setCommandResolverForTests,
  setKickProcessExecutor,
  spawnAgent,
  type Transport,
  WorkspacePreservedError,
} from "./agents.js";
export {
  type ApplyResult,
  applyOp,
  applyOps,
  type Op,
  OpEntityNotSyncedError,
  OpKeyMalformedError,
} from "./apply.js";
export {
  CAPTURE_TRIGGER_DDL,
  type CaptureDb,
  installCapture,
  OP_CTX_DDL,
} from "./capture.js";
export {
  type FullDag,
  type LoadFullDagOptions,
  loadFullDag,
  renderForest,
  renderTaskTree,
} from "./dag.js";
export {
  CURRENT_SCHEMA_VERSION,
  type Db,
  defaultDbPath,
  defaultStateDir,
  EXPECTED_TABLES,
  MACHINE_LOCAL_ENTITIES,
  MACHINE_LOCAL_TABLES,
  type MachineLocalEntity,
  type MachineLocalTable,
  type OpenDbOptions,
  openDb,
  PORTABLE_TABLES,
  type PortableTable,
  SchemaTooOldError,
  SYNCED_ENTITIES,
  type SyncedEntity,
} from "./db.js";
export {
  countProblems,
  type DoctorCheck,
  type DoctorStatus,
  type DoctorSummary,
  loadDoctorChecks,
  loadDoctorSummary,
  remediationParagraph,
  yankCommandForCheck,
} from "./doctor-summary.js";
export {
  type CheapDriftReport,
  checkCheapDriftInvariant,
  checkDrift,
  DRIFT_REPORT_CAP,
  DriftDetectedError,
  type DriftRecord,
  type DriftReport,
  driftRemediation,
  formatDriftRecord,
} from "./drift.js";
export {
  type FileLockOptions,
  locksDir,
  readFileLockMeta,
  withFileLock,
} from "./file-lock.js";
export {
  type CaseCollision,
  checkCaseCollisions,
  checkDbInsideSyncDir,
  checkFleetHazards,
  checkNetworkMount,
  classifyFsType,
  type FleetHazard,
  type FsProbe,
  findCaseCollisions,
  type HazardSeverity,
  isPathInside,
  probeFilesystem,
} from "./fleet-hazards.js";
export { AGENT_STATE_GLYPH, agentStateGlyph, GLYPH } from "./glyphs.js";
export {
  compareHlc,
  formatHlc,
  type Hlc,
  HlcOverflowError,
  HlcParseError,
  MachineIdentityMissingError,
  nextHlc,
  parseHlc,
  receiveHlc,
} from "./hlc.js";
export {
  inspectLinks,
  LinkConflictError,
  type LinkState,
  type LinkStatus,
  linkPi,
  linkSkill,
  MU_SHIM_MARKER,
} from "./link.js";
export {
  type CaptureIntent,
  KNOWN_INTENTS,
  KNOWN_VERBS,
  type KnownIntent,
  opSubject,
  parseOpKey,
  type RenderableOp,
  type RenderedOp,
  renderOp,
  renderOpLine,
} from "./log-render.js";
export {
  type AppendLogOptions,
  appendLog,
  emitEvent,
  type ListLogsOptions,
  type LocalIntent,
  type LogKind,
  type LogRow,
  latestSeq,
  listLogs,
} from "./logs.js";
export * as mux from "./mux.js";
export {
  activeMux,
  detectMux,
  type MuxBackend,
  type MuxBackendName,
  MuxError,
  type MuxPane,
  type MuxPaneStatus,
  type MuxSession,
  type MuxWindow,
  muxByName,
  NoMultiplexerError,
  resetMux,
  setMuxForTests,
  tmuxBackend,
} from "./mux.js";
export {
  currentOpContext,
  type OpContext,
  withCaptureSuppressed,
  withOpContext,
} from "./op-context.js";
export {
  type MachineLocalLoss,
  type RebuildOptions,
  type RebuildReport,
  RebuildTargetExistsError,
  RebuildTargetIsSourceError,
  rebuildInto,
} from "./rebuild.js";
export {
  type ReconcileMode,
  type ReconcileOptions,
  type ReconcileReport,
  reconcile,
} from "./reconcile.js";
export {
  applyIncomingOp,
  discoverPeers,
  type FlushResult,
  flushSegment,
  getWatermark,
  type IngestResult,
  ingestSegment,
  localMachineId,
  type PeerSegment,
  readManifest,
  resetWatermark,
  SEGMENT_FORMAT_VERSION,
  type SegmentDefect,
  type SegmentDefectKind,
  type SegmentLine,
  type SegmentManifest,
  type SyncPassResult,
  segmentLineCount,
  segmentPath,
  setWatermark,
  syncDir,
  syncPass,
  verifyAgainstManifest,
} from "./segments.js";
export {
  agentStateHistogram,
  type LoadWorkstreamSnapshotOptions,
  loadWorkstreamSnapshot,
  loadWorkstreamSnapshotFast,
  loadWorkstreamSnapshotSlow,
  mergeSnapshotFastSlow,
  type OwnedTasksSummary,
  type RoiBucket,
  roiBucket,
  summarizeOwnedTasks,
  type WorkstreamSnapshot,
  type WorkstreamSnapshotSlowFields,
} from "./state.js";
export {
  type AmbientOptions,
  type AmbientResult,
  ambientFlush,
  ambientIngest,
  ambientSyncPass,
  type IngestFromDbResult,
  ingestFromDb,
  PEER_SHORT_LEN,
  PEER_STALE_MS,
  type PeerStatus,
  peerStatuses,
  repairPeer,
  resolvePeerRef,
  SyncPeerNotFoundError,
  SyncPeerRefAmbiguousError,
  SyncSourceNotFoundError,
  syncEnabled,
  transportNextSteps,
} from "./sync.js";
export {
  type AddNoteOptions,
  type AddTaskOptions,
  acceptTask,
  addBlockEdge,
  addNote,
  addTask,
  type BlockEdgeResult,
  ClaimerNotRegisteredError,
  type ClaimResult,
  type ClaimTaskOptions,
  type CloseSubstate,
  type CloseTaskResult,
  CrossWorkstreamEdgeError,
  CycleError,
  claimTask,
  closeTask,
  DEFAULT_SUBSTATE,
  type DeleteTaskResult,
  deleteTask,
  type EvidenceOption,
  formatPair,
  getPrerequisites,
  getTask,
  getTaskEdges,
  getTaskEdgesWithStatus,
  getWaitPollCount,
  type IdFromTitleResult,
  InvalidSubstateError,
  idFromTitle,
  idFromTitleVerbose,
  isTaskStatus,
  isValidPair,
  isValidTaskId,
  type ListNotesOptions,
  type ListReadyOptions,
  type ListTasksOptions,
  listBlocked,
  listGoals,
  listInProgress,
  listNotes,
  listReady,
  listRecentClosed,
  listTasks,
  listTasksByOwner,
  mapLegacyStatus,
  openTask,
  type ParkTaskOptions,
  parkTask,
  type ReleaseResult,
  type ReleaseTaskOptions,
  type RemoveBlockEdgeResult,
  type ReparentTaskResult,
  releaseTask,
  removeBlockEdge,
  reparentTask,
  resetWaitPollCount,
  resolveActorIdentity,
  resolvePair,
  type SetStatusOptions,
  type SetStatusResult,
  type SlugifyResult,
  SubstateReasonRequiredError,
  setTaskStatus,
  setWaitSleepForTests,
  setWaitStuckWarnForTests,
  slugifyTitle,
  slugifyTitleVerbose,
  TASK_STATUS_LIST,
  TASK_STATUSES,
  TASK_SUBSTATE_ROWS,
  TASK_SUBSTATES,
  TaskAlreadyOwnedError,
  type TaskEdges,
  type TaskEdgesWithStatus,
  type TaskEdgeWithStatus,
  TaskExistsError,
  TaskInTriageError,
  type TaskNoteRow,
  TaskNotFoundError,
  TaskNotInWorkstreamError,
  type TaskPair,
  TaskParkedError,
  TaskParkStateError,
  type TaskRow,
  type TaskStatus,
  type TaskSubstate,
  type TaskWaitOptions,
  type TaskWaitRef,
  type TaskWaitResult,
  type TaskWaitTaskState,
  type UpdateTaskOptions,
  type UpdateTaskResult,
  unparkTask,
  updateTask,
  waitForTasks,
} from "./tasks.js";
export * as tmux from "./tmux.js";
export {
  assertValidPaneId,
  awaitPaneQuiescence,
  type CaptureOptions,
  capturePane,
  currentAgentName,
  currentPaneTitle,
  defaultSendDelayMs,
  defaultSendReadinessMs,
  hasWorkMarker,
  isValidPaneId,
  killPane,
  killSession,
  listPanes,
  listPanesInSession,
  listSessions,
  listWindows,
  type NewSessionOptions,
  type NewWindowOptions,
  newSession,
  newSessionWithPane,
  newWindow,
  PANE_ID_RE,
  PaneNotFoundError,
  paneExists,
  paneTTY,
  parseAgentNameFromTitle,
  resetSleep,
  resetTmuxExecutor,
  type SendOptions,
  type SendWarning,
  type SplitWindowOptions,
  selectLayout,
  sendToPane,
  sessionExists,
  setPaneTitle,
  setSleepForTests,
  setTmuxExecutor,
  sleep,
  splitWindow,
  TmuxError,
  type TmuxExecResult,
  type TmuxExecutor,
  type TmuxPane,
  type TmuxSession,
  type TmuxWindow,
} from "./tmux.js";
export { getParallelTracks, type Track } from "./tracks.js";
export {
  type GroupSummary,
  type InverseOp,
  listRecentGroups,
  mostRecentGroup,
  NothingToUndoError,
  planUndo,
  priorFieldValue,
  resolveGroupId,
  UndoGroupNotFoundError,
  type UndoOptions,
  type UndoPlan,
  type UndoResult,
  UndoSupersededError,
  undoGroup,
} from "./undo.js";
export {
  backendByName,
  detectBackend,
  gitBackend,
  jjBackend,
  noneBackend,
  slBackend,
  type VcsBackend,
  type VcsBackendName,
} from "./vcs.js";
export {
  createWorkspace,
  decorateWithDirty,
  decorateWithStaleness,
  freeWorkspace,
  getWorkspaceForAgent,
  getWorkspaceStaleness,
  HomeDirAsProjectRootError,
  isWorkspaceStale,
  listAllOrphanWorkspaces,
  listWorkspaceOrphans,
  listWorkspaces,
  type StrandedWorkspaceOrphan,
  WORKSPACE_STALE_THRESHOLD,
  WorkspaceExistsError,
  WorkspaceNotFoundError,
  type WorkspaceOrphan,
  WorkspacePathNotEmptyError,
  type WorkspaceRow,
  type WorkspaceStaleness,
  workspacePath,
  workspacesRoot,
} from "./workspace.js";
export {
  ensureWorkstream,
  isValidWorkstreamName,
  listWorkstreams,
  summarizeWorkstream,
  type TeardownResult,
  teardownWorkstream,
  type WorkspaceFailure,
  WorkstreamExistsError,
  WorkstreamNameInvalidError,
  type WorkstreamOptions,
  type WorkstreamSummary,
} from "./workstream.js";
